# SPDX-License-Identifier: Apache-2.0
# birc provisioning. Bend 2 is pinned as a non-flake source input; its
# identity (rev + narHash) lives in flake.lock, generated by `make bootstrap`
# (nix flake lock), never hand-written. Routine targets use
# --no-update-lock-file; only `make update CONFIRM=yes` may move pins.
{
  description = "birc — IRC client in Bend 2 + timui.h";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

  # Bend 2 (bendlang/bend), pinned to an immutable commit.
  inputs.bend-src = {
    url = "github:bendlang/bend/f38a7797a98e931ae99eb49881ff4bef127b34ca";
    flake = false;
  };

  outputs = { self, nixpkgs, bend-src }:
    let
      systems = [ "aarch64-darwin" "x86_64-linux" "aarch64-linux" "x86_64-darwin" ];
      forAllSystems = nixpkgs.lib.genAttrs systems;
    in {
      packages = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          bend = pkgs.callPackage ./nix/bend.nix { inherit bend-src; };
          birc = pkgs.callPackage ./nix/birc.nix { inherit bend; };
        in {
          inherit bend birc;
          default = birc;
        });

      apps = forAllSystems (system: {
        default = {
          type = "app";
          program = "${self.packages.${system}.birc}/bin/birc";
        };
        birc = {
          type = "app";
          program = "${self.packages.${system}.birc}/bin/birc";
        };
      });

      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          bend = self.packages.${system}.bend;
        in {
          default = pkgs.mkShell {
            packages = with pkgs; [
              bend bun clang python3
              bashInteractive gnumake git
              coreutils findutils gnugrep gnused gawk
              diffutils file which cacert
            ];
            BIRC_NIX_SHELL = "1";
            BIRC_BEND_SRC = "${bend-src}";
            BIRC_BEND_REV = "f38a7797a98e931ae99eb49881ff4bef127b34ca";
            CC = "${pkgs.clang}/bin/clang";
            shellHook = ''
              export PYTHONDONTWRITEBYTECODE=1
            '';
          };
        });
    };
}
